global:
  resolve_timeout: 1m

route:
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 10s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 30m

  # A default receiver
  receiver: "slack"

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.
  routes:
    - receiver: "slack"
      group_wait: 10s
      match_re:
        severity: critical|warning
      continue: true

    - receiver: "email"
      group_wait: 10s
      match_re:
        severity: critical|warning
      continue: true

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'prometheus'
            channel: '#devops'
            api_url: 'your webhook url'

    - name: 'email'
      email_configs:
        - to: 'mehdi.taieb.safe@gmail.com'
          from: 'mehdi.taieb.sa.fe@gmail.com'
          smarthost: smtp.gmail.com:587
          auth_username: 'mehdi.taieb.safe@gmail.com'
          auth_identity: 'mehdi.taieb.safe@gmail.com'
          auth_password: 'tgrohsrplqfbdwrp'
          send_resolved: true
