version: '3.7'

services:

  master:
    build: /ubuntu/.
    container_name: master
    volumes:
      - master_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      org.label-schema.group: "monitoring"
      
  node1:
    build: /ubuntu/.
    container_name: node1
    volumes:
      - node_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      org.label-schema.group: "monitoring" 
  node2:
    build: /ubuntu/.
    container_name: node2
    volumes:
      - node_data:/data
    labels:
      org.label-schema.group: "monitoring"

  
