version: '3.7'

services:

  master:
    image: centos
    container_name: master
    volumes:
      - master_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 9090

    labels:
      org.label-schema.group: "monitoring"
      
  node1:
    image: centos
    container_name: node1
    volumes:
      - node_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

    expose:
      - 9090

    labels:
      org.label-schema.group: "monitoring" 
  node2:
    image: centos
    container_name: node2
    volumes:

      - node_data:/data

    expose:
      - 9090
    labels:
      org.label-schema.group: "monitoring"

  
